<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>FilipinoFolkloreApp</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>FilipinoFolkloreApp</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.filipinofolkloreapp</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
		
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|AnyCPU'">
	  <AndroidPackageFormat>apk</AndroidPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<!--<MauiSplashScreen Include="Resources\Splash\splash.jpg" Color="#512BD4" />-->

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <AndroidResource Remove="Platforms\Android\Resources\values\launch_background.xml" />
	  <AndroidResource Remove="Platforms\Android\Resources\values\styles.xml" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\Images\avatarcustomization\avatar1\avatar1_blue.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar1\avatar1_bluered.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar1\avatar1_red.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar1\avatar1_whiteblue.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar1\avatar1_whitered.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar2\avatar2_blue.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar2\avatar2_bluered.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar2\avatar2_red.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar2\avatar2_whiteblue.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar2\avatar2_whitered.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar3\avatar3.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar3\avatar3_white.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar3\avatar3_whiteblack.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar3\avatar3_whitegreen.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar3\avatar3_whiteorange.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar3\avatar3_whitered.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar4\avatar4.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar4\avatar4_white.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar4\avatar4_whiteblack.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar4\avatar4_whitegreen.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar4\avatar4_whiteorange.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar4\avatar4_whitered.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar_blue.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar_bluered.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar_green.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar_pink.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar_red.png" />
	  <None Remove="Resources\Images\avatarcustomization\avatar_white.png" />
	  <None Remove="Resources\Images\avatarcustomization\defaultavatar.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis\bblue.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis\bbluered.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis\bred.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis\bwhiteblue.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis\bwhitered.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis\gwhite.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis\gwhiteblack.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis\gwhitegreen.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis\gwhiteorange.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis\gwhitered.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis_blue.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis_bluered.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis_green.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis_pink.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis_red.png" />
	  <None Remove="Resources\Images\avatarcustomization\tapis_white.png" />
	  <None Remove="Resources\Images\bg\avatar_bg.jpg" />
	  <None Remove="Resources\Images\bg\char_choicebg.jpg" />
	  <None Remove="Resources\Images\bg\homepage_bg.jpg" />
	  <None Remove="Resources\Images\bg\login_bg.jpg" />
	  <None Remove="Resources\Images\bg\narator_bg.jpg" />
	  <None Remove="Resources\Images\bg\reward_bg.jpg" />
	  <None Remove="Resources\Images\elements\close.png" />
	  <None Remove="Resources\Images\elements\eagle.png" />
	  <None Remove="Resources\Images\elements\lock.png" />
	  <None Remove="Resources\Images\elements\monkey.png" />
	  <None Remove="Resources\Images\elements\next.png" />
	  <None Remove="Resources\Images\elements\pause.png" />
	  <None Remove="Resources\Images\elements\play.png" />
	  <None Remove="Resources\Images\elements\prev.png" />
	  <None Remove="Resources\Images\medals\basa.png" />
	  <None Remove="Resources\Images\medals\harireyna.png" />
	  <None Remove="Resources\Images\medals\kaibigankwento.png" />
	  <None Remove="Resources\Images\medals\kasangga.png" />
	  <None Remove="Resources\Images\medals\lakambantay.png" />
	  <None Remove="Resources\Images\medals\lakambayanihan.png" />
	  <None Remove="Resources\Images\medals\lakbaykultura.png" />
	  <None Remove="Resources\Images\medals\lakbaykwento.png" />
	  <None Remove="Resources\Images\medals\likhakulay.png" />
	  <None Remove="Resources\Images\medals\lipad.png" />
	  <None Remove="Resources\Images\medals\mananalaysay.png" />
	  <None Remove="Resources\Images\medals\manlalarobituin.png" />
	  <None Remove="Resources\Images\medals\mapanlikha.png" />
	  <None Remove="Resources\Images\medals\medal1.jpg" />
	  <None Remove="Resources\Images\medals\medal10.jpg" />
	  <None Remove="Resources\Images\medals\medal11.jpg" />
	  <None Remove="Resources\Images\medals\medal12.jpg" />
	  <None Remove="Resources\Images\medals\medal13.jpg" />
	  <None Remove="Resources\Images\medals\medal14.jpg" />
	  <None Remove="Resources\Images\medals\medal15.jpg" />
	  <None Remove="Resources\Images\medals\medal2.jpg" />
	  <None Remove="Resources\Images\medals\medal3.jpg" />
	  <None Remove="Resources\Images\medals\medal4.jpg" />
	  <None Remove="Resources\Images\medals\medal5.jpg" />
	  <None Remove="Resources\Images\medals\medal6.jpg" />
	  <None Remove="Resources\Images\medals\medal7.jpg" />
	  <None Remove="Resources\Images\medals\medal8.jpg" />
	  <None Remove="Resources\Images\medals\medal9.jpg" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan1.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan10.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan11.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan12.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan13.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan14.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan15.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan2.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan3.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan4.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan5.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan6.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan7.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan8.png" />
	  <None Remove="Resources\Images\storiesepiko\bantugan\bantugan9.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon1.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon10.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon11.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon12.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon13.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon14.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon2.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon3.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon4.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon5.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon6.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon7.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon8.png" />
	  <None Remove="Resources\Images\storiesepiko\ibalon\ibalon9.png" />
	  <None Remove="Resources\Images\storiesepiko\kudaman\kudaman1.png" />
	  <None Remove="Resources\Images\storiesepiko\kudaman\kudaman2.png" />
	  <None Remove="Resources\Images\storiesepiko\kudaman\kudaman3.png" />
	  <None Remove="Resources\Images\storiesepiko\kudaman\kudaman4.png" />
	  <None Remove="Resources\Images\storiesepiko\kudaman\kudaman5.png" />
	  <None Remove="Resources\Images\storiesepiko\kudaman\kudaman6.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya1.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya2.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya3.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya4.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya5.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya6.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya7.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing1.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing10.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing11.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing12.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing13.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing14.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing15.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing16.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing2.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing3.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing4.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing5.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing6.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing7.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing8.png" />
	  <None Remove="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing9.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho1.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho10.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho11.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho12.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho13.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho14.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho15.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho16.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho2.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho3.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho4.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho5.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho6.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho7.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho8.png" />
	  <None Remove="Resources\Images\storiespabula\pagong_at_kuneho9.png" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hills1.png" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hills10.png" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hills11.png" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hills12.jpg" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hills13.png" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hills2.png" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hills3.png" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hills4.png" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hills5.png" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hills6.png" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hills7.png" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hills8.png" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hills9.png" />
	  <None Remove="Resources\Images\stories\chocolatehills\chocolate_hillsicon.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad1.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad10.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad11.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad12.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad13.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad14.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad15.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad16.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad2.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad3.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad4.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad5.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad6.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad7.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad8.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad9.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad_scene1.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad_scene2.png" />
	  <None Remove="Resources\Images\stories\juantamad\juan_tamad_thumb.png" />
	  <None Remove="Resources\Images\stories\juantamad\quiz1\juantamad_quiz1A.png" />
	  <None Remove="Resources\Images\stories\juantamad\quiz1\juantamad_quiz1B.png" />
	  <None Remove="Resources\Images\stories\juantamad\quiz1\juantamad_quiz1C.png" />
	  <None Remove="Resources\Images\storiesepiko\lapulapu\lapulapu_scene1.png" />
	  <None Remove="Resources\Images\storiesepiko\lapulapu\lapulapu_scene2.png" />
	  <None Remove="Resources\Images\storiesepiko\lapulapu\lapulapu_thumbnail.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="9.1.1" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
		<PackageReference Include="Plugin.Maui.Audio" Version="4.0.0" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Views\AlamatPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\AvatarSelectionPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CharacterCostume.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Home\IndexPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MedalDetailPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MedalPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NarratorPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\QuizPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\RewardPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\StoryPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Platforms\Android\Resources\mipmap\" />
	  <Folder Include="Views\NewFolder\" />
	  <Folder Include="Views\Popup\" />
	</ItemGroup>

	<ItemGroup>
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar1\avatar1.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar1\avatar1_blue.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar1\avatar1_bluered.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar1\avatar1_red.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar1\avatar1_whiteblue.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar1\avatar1_whitered.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar2\avatar2.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar2\avatar2_blue.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar2\avatar2_bluered.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar2\avatar2_red.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar2\avatar2_whiteblue.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar2\avatar2_whitered.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar3\avatar3.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar3\avatar3_white.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar3\avatar3_whiteblack.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar3\avatar3_whitegreen.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar3\avatar3_whiteorange.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar3\avatar3_whitered.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar4\avatar4.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar4\avatar4_white.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar4\avatar4_whiteblack.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar4\avatar4_whitegreen.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar4\avatar4_whiteorange.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\avatar4\avatar4_whitered.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\tapis\bblue.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\tapis\bbluered.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\tapis\bred.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\tapis\bwhiteblue.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\tapis\bwhitered.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\tapis\gwhite.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\tapis\gwhiteblack.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\tapis\gwhitegreen.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\tapis\gwhiteorange.png" />
	  <MauiImage Include="Resources\Images\avatarcustomization\tapis\gwhitered.png" />
	  <MauiImage Include="Resources\Images\bg\avatar_bg.jpg" />
	  <MauiImage Include="Resources\Images\bg\char_choicebg.jpg" />
	  <MauiImage Include="Resources\Images\bg\homepage_bg.jpg" />
	  <MauiImage Include="Resources\Images\bg\login_bg.jpg" />
	  <MauiImage Include="Resources\Images\bg\narator_bg.jpg" />
	  <MauiImage Include="Resources\Images\bg\reward_bg.jpg" />
	  <MauiImage Include="Resources\Images\elements\close.png" />
	  <MauiImage Include="Resources\Images\elements\eagle.png" />
	  <MauiImage Include="Resources\Images\elements\lock.png" />
	  <MauiImage Include="Resources\Images\elements\monkey.png" />
	  <MauiImage Include="Resources\Images\elements\next.png" />
	  <MauiImage Include="Resources\Images\elements\pause.png" />
	  <MauiImage Include="Resources\Images\elements\play.png" />
	  <MauiImage Include="Resources\Images\elements\prev.png" />
	  <MauiImage Include="Resources\Images\keys\a.png" />
	  <MauiImage Include="Resources\Images\keys\b.png" />
	  <MauiImage Include="Resources\Images\keys\c.png" />
	  <MauiImage Include="Resources\Images\keys\d.png" />
	  <MauiImage Include="Resources\Images\keys\e.png" />
	  <MauiImage Include="Resources\Images\keys\f.png" />
	  <MauiImage Include="Resources\Images\keys\g.png" />
	  <MauiImage Include="Resources\Images\keys\h.png" />
	  <MauiImage Include="Resources\Images\keys\i.png" />
	  <MauiImage Include="Resources\Images\keys\j.png" />
	  <MauiImage Include="Resources\Images\keys\k.png" />
	  <MauiImage Include="Resources\Images\keys\l.png" />
	  <MauiImage Include="Resources\Images\keys\m.png" />
    <MauiImage Include="Resources\Images\keys\n.png" />
	  <MauiImage Include="Resources\Images\keys\o.png" />
    <MauiImage Include="Resources\Images\keys\p.png" />
    <MauiImage Include="Resources\Images\keys\q.png" />
    <MauiImage Include="Resources\Images\keys\r.png" />
    <MauiImage Include="Resources\Images\keys\s.png" />
	  <MauiImage Include="Resources\Images\keys\t.png" />
    <MauiImage Include="Resources\Images\keys\u.png" />
    <MauiImage Include="Resources\Images\keys\v.png" />
    <MauiImage Include="Resources\Images\keys\w.png" />
    <MauiImage Include="Resources\Images\keys\x.png" />
    <MauiImage Include="Resources\Images\keys\y.png" />
    <MauiImage Include="Resources\Images\keys\z.png" />
    <MauiImage Include="Resources\Images\keys\ok.png" />

		<!--avatar-->

		<!---background-->
    <MauiImage Include="Resources\Images\bg\selectionpage.jpg" />
    <MauiImage Include="Resources\Images\bg\image4.jpg" />

    <!---elements-->
    <MauiImage Include="Resources\Images\elements\star.png" />
    <MauiImage Include="Resources\Images\elements\tarsier.png" />
    <MauiImage Include="Resources\Images\elements\pluss.png" />
    <MauiImage Include="Resources\Images\medals\basa.png" />
    <MauiImage Include="Resources\Images\medals\harireyna.png" />
    <MauiImage Include="Resources\Images\medals\kaibigankwento.png" />
    <MauiImage Include="Resources\Images\medals\kasangga.png" />
    <MauiImage Include="Resources\Images\medals\lakambantay.png" />
    <MauiImage Include="Resources\Images\medals\lakambayanihan.png" />
    <MauiImage Include="Resources\Images\medals\lakbaykultura.png" />
    <MauiImage Include="Resources\Images\medals\lakbaykwento.png" />
    <MauiImage Include="Resources\Images\medals\likhakulay.png" />
    <MauiImage Include="Resources\Images\medals\lipad.png" />
    <MauiImage Include="Resources\Images\medals\mananalaysay.png" />
    <MauiImage Include="Resources\Images\medals\manlalarobituin.png" />
    <MauiImage Include="Resources\Images\medals\mapanlikha.png" />
    <MauiImage Include="Resources\Images\medals\medal1.jpg" />
    <MauiImage Include="Resources\Images\medals\medal10.jpg" />
    <MauiImage Include="Resources\Images\medals\medal11.jpg" />
    <MauiImage Include="Resources\Images\medals\medal12.jpg" />
    <MauiImage Include="Resources\Images\medals\medal13.jpg" />
    <MauiImage Include="Resources\Images\medals\medal14.jpg" />
    <MauiImage Include="Resources\Images\medals\medal15.jpg" />
    <MauiImage Include="Resources\Images\medals\medal2.jpg" />
    <MauiImage Include="Resources\Images\medals\medal3.jpg" />
    <MauiImage Include="Resources\Images\medals\medal4.jpg" />
    <MauiImage Include="Resources\Images\medals\medal5.jpg" />
    <MauiImage Include="Resources\Images\medals\medal6.jpg" />
    <MauiImage Include="Resources\Images\medals\medal7.jpg" />
    <MauiImage Include="Resources\Images\medals\medal8.jpg" />
    <MauiImage Include="Resources\Images\medals\medal9.jpg" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan1.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan10.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan11.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan12.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan13.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan14.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan15.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan2.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan3.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan4.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan5.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan6.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan7.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan8.png" />
    <MauiImage Include="Resources\Images\storiesepiko\bantugan\bantugan9.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon1.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon10.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon11.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon12.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon13.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon14.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon2.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon3.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon4.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon5.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon6.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon7.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon8.png" />
    <MauiImage Include="Resources\Images\storiesepiko\ibalon\ibalon9.png" />
    <MauiImage Include="Resources\Images\storiesepiko\kudaman\kudaman1.png" />
    <MauiImage Include="Resources\Images\storiesepiko\kudaman\kudaman2.png" />
    <MauiImage Include="Resources\Images\storiesepiko\kudaman\kudaman3.png" />
    <MauiImage Include="Resources\Images\storiesepiko\kudaman\kudaman4.png" />
    <MauiImage Include="Resources\Images\storiesepiko\kudaman\kudaman5.png" />
    <MauiImage Include="Resources\Images\storiesepiko\kudaman\kudaman6.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya1.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya2.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya3.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya4.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya5.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya6.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatbuwaya\pagong_at_buwaya7.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho1.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho10.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho11.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho12.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho13.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho14.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho15.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho16.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho2.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho3.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho4.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho5.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho6.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho7.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho8.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatkuneho\pagong_at_kuneho9.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing1.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing10.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing11.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing12.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing13.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing14.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing15.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing16.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing2.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing3.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing4.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing5.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing6.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing7.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing8.png" />
    <MauiImage Include="Resources\Images\storiespabula\pagongatmatsing\pagong_at_matsing9.png" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hills1.png" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hills10.png" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hills11.png" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hills12.jpg" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hills13.png" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hills2.png" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hills3.png" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hills4.png" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hills5.png" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hills6.png" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hills7.png" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hills8.png" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hills9.png" />
    <MauiImage Include="Resources\Images\stories\chocolatehills\chocolate_hillsicon.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad1.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad10.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad11.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad12.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad13.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad14.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad15.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad16.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad2.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad3.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad4.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad5.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad6.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad7.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad8.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad9.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad_scene1.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad_scene2.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\juan_tamad_thumb.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\quiz1\juantamad_quiz1a.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\quiz1\juantamad_quiz1b.png" />
    <MauiImage Include="Resources\Images\stories\juantamad\quiz1\juantamad_quiz1c.png" />
    <MauiImage Include="Resources\Images\storiesepiko\lapulapu\lapulapu_scene1.png" />
    <MauiImage Include="Resources\Images\storiesepiko\lapulapu\lapulapu_scene2.png" />
    <MauiImage Include="Resources\Images\storiesepiko\lapulapu\lapulapu_thumbnail.png" />
    <MauiImage Include="Resources\Images\stories\langit\langit1.png" />
    <MauiImage Include="Resources\Images\stories\langit\langit2.png" />
    <MauiImage Include="Resources\Images\stories\langit\langit3.png" />
    <MauiImage Include="Resources\Images\stories\langit\langit4.png" />
    <MauiImage Include="Resources\Images\stories\langit\langit5.png" />
    <MauiImage Include="Resources\Images\stories\langit\langit6.png" />
    <MauiImage Include="Resources\Images\stories\langit\langit7.png" />
	</ItemGroup>

	<ItemGroup>
	  <MauiAsset Update="Resources\Raw\storiesalamat\juantamad\audio\juantamad_tarsier2.mp3">
	    <CopyToOutputDirectory></CopyToOutputDirectory>
	  </MauiAsset>
	  <MauiAsset Update="Resources\Raw\storiesalamat\juantamad\audio\juantamad_tarsier1.mp3">
	    <CopyToOutputDirectory></CopyToOutputDirectory>
	  </MauiAsset>
	</ItemGroup>

</Project>
